import type { ComputeResult, Pursuit } from '../engine';
import { addMonths, fileSafe, money0, pct } from '../lib/format';
import { downloadBlob } from './download';

/**
 * Proposal extract as a genuine .docx (the prototype downloaded HTML with a
 * .doc extension, which Word flags as suspicious). docx is bundled and
 * loaded on demand.
 */
export async function exportWord(s: Pursuit, r: ComputeResult) {
  const { Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } = await import('docx');
  const c = s.control;

  const cell = (text: string, bold = false) =>
    new TableCell({
      children: [new Paragraph({ children: [new TextRun({ text, bold, size: 18 })] })],
      width: { size: 25, type: WidthType.PERCENTAGE },
    });

  const table = (head: string[], rows: string[][]) =>
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({ children: head.map((h) => cell(h, true)) }),
        ...rows.map((row) => new TableRow({ children: row.map((x) => cell(x)) })),
      ],
    });

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({ text: 'Astrion — Pricing Volume', heading: HeadingLevel.HEADING_1 }),
          new Paragraph({ text: s.name, heading: HeadingLevel.HEADING_2 }),
          new Paragraph({
            children: [
              new TextRun({ text: `Total Price (${c.confidence}): `, bold: true }),
              new TextRun(money0(r.total)),
              new TextRun({ text: '   Phase 1: ', bold: true }),
              new TextRun(money0(r.phase1Price)),
              new TextRun({ text: '   Phase 2: ', bold: true }),
              new TextRun(money0(r.phase2Price)),
            ],
          }),
          new Paragraph(
            `Cost P50 ${money0(r.costP50)}; Cost P80 ${money0(r.costP80)}; reserve ${pct(r.resPct)}; fee ${pct(c.fee)}; gross-up ${r.grossup.toFixed(3)}x.`,
          ),
          new Paragraph({ text: 'Milestone Payment Schedule', heading: HeadingLevel.HEADING_3 }),
          table(
            ['ALIN', 'Milestone', 'Est. Completion', 'Payable Price'],
            r.msRows.map((m) => [
              m.phase === 1 ? 'ALIN 001' : 'ALIN 002',
              m.name,
              addMonths(c.popStart, m.monthOffset),
              money0(m.price),
            ]),
          ),
          new Paragraph({ text: 'Basis of Estimate', heading: HeadingLevel.HEADING_3 }),
          table(
            ['Element', 'Epics', 'Sprints', 'Labor', 'Price'],
            [
              ...r.boeCaps.map((b) => [b.element, String(b.epics), b.sprints.toFixed(1), money0(b.labor), money0(b.price)]),
              ...r.boeExtra.map((b) => [b.element, '', '', money0(b.totalCost), money0(b.price)]),
            ],
          ),
          new Paragraph({
            children: [
              new TextRun({
                text: 'Generated by Astrion Agile Pricing Studio. Illustrative placeholders; populate controlled data only in an accredited environment.',
                size: 16,
                color: '888888',
              }),
            ],
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, fileSafe(s.name) + '_Pricing.docx');
}
